import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';
import { remarkInternalLinks, remarkFolderImages, remarkImageCaptions } from './src/utils/internallinks.ts';
import remarkCallouts from './src/utils/remark-callouts.ts';
import remarkRescueCurrency from './src/utils/remark-rescue-currency.ts';
import remarkImageGrids from './src/utils/remark-image-grids.ts';
import remarkMermaid from './src/utils/remark-mermaid.ts';
import { remarkObsidianEmbeds } from './src/utils/remark-obsidian-embeds.ts';
import remarkBases from './src/utils/remark-bases.ts';
import remarkInlineTags from './src/utils/remark-inline-tags.ts';
import { remarkObsidianComments } from './src/utils/remark-obsidian-comments.ts';
import remarkObsidianImageSize from './src/utils/remark-obsidian-image-size.ts';
import remarkMath from 'remark-math';
import remarkReadingTime from 'remark-reading-time';
import remarkToc from 'remark-toc';
import remarkBreaks from 'remark-breaks';
import rehypeKatex from 'rehype-katex';
import rehypeMark from './src/utils/rehype-mark.ts';
import rehypeImageAttributes from './src/utils/rehype-image-attributes.ts';
import { rehypeNormalizeAnchors } from './src/utils/rehype-normalize-anchors.ts';
import rehypeRebaseLinks from './src/utils/rehype-rebase-links.ts';
import rehypeFigureCaptions from './src/utils/rehype-figure-captions.ts';
import rehypeSlug from 'rehype-slug';
import rehypeAutolinkHeadings from 'rehype-autolink-headings';
import { rehypeHeadingHighlight } from './src/utils/rehype-heading-highlight.ts';
import { siteConfig } from './src/config.ts';
import { remarkMarginalia } from './src/utils/remark-marginalia.ts';
import remarkAnnotations from './src/utils/remark-annotations.ts';
import remarkCitations from './src/utils/remark-citations.ts';
import swup from '@swup/astro';
import pagefind from 'astro-pagefind';
import refreshContentOnChange from './src/integrations/refresh-content-on-change.ts';
import { fileURLToPath } from 'node:url';

// Deployment platform configuration
const DEPLOYMENT_PLATFORM = process.env.DEPLOYMENT_PLATFORM || 'netlify';
const isGitHubPages = DEPLOYMENT_PLATFORM === 'github-pages';

export default defineConfig({
  site: siteConfig.site,
  trailingSlash: 'always',
  prefetch: true,
  base: undefined,
  deployment: {
    platform: DEPLOYMENT_PLATFORM
  },
  // NOTE: Content-Security-Policy is NOT configured here. Astro's `csp` option
  // does not apply to this static Cloudflare Workers build (it emits nothing).
  // The live CSP ships as an HTTP header from dist/_headers — edit it in
  // scripts/generate-deployment-config.js (the `CSP` constant).
  devToolbar: {
    enabled: true
  },
  redirects: (process.env.NODE_ENV !== 'production' && process.env.NODE_ENV !== 'build') ? {
  '/posts/the-johannine-comma-from-christian-references-1-john5-7': '/posts/1-john-5-7-the-johannine-comma-a-fabricated-addition-to-the-bible',
  '/posts/1-john-not-written-by-john-or-the-apostle': '/posts/1-john-authorship-anonymous-letter-with-no-confirmed-link-to-the-apostle-john',
  '/posts/historical-error-in-the-bible-shishaks-alleged-campaign-on-jerusalem': '/posts/1-kings-14-2528-and-the-shishak-campaign-jerusalem-does-not-appear-in-the-egyptian-record',
  '/posts/7-hijab-doubts': '/posts/7-common-doubts-about-the-hijab-and-how-islam-answers-every-one',
  '/posts/seventy-five-questions-about-christianity-that-have-no-answer': '/posts/74-questions-on-biblical-contradictions-theology-and-the-crucifixion-claim',
  '/posts/b': '/posts/a-disbeliever-and-his-killer-will-never-meet-in-hell-explained',
  '/posts/abdullah-bin-saad-bin-abi-sarh': '/posts/abdullah-bin-saad-bin-abi-sarh-apostasy-claim-refuted-through-hadith-chains-and-textual-criticism',
  '/posts/story-of-abrahas-elephant-and-how-the-elephant-traveled-in-the-desert-and-can-the-elephant-walk-in': '/posts/abrahas-elephant-can-an-elephant-walk-from-yemen-to-mecca-every-doubt-refuted',
  '/posts/what-is-abrogation': '/posts/abrogation-in-islam-explained-refuting-christian-claims-about-naskh-and-quran-preservation',
  '/posts/a-claim-to-deny-the-hadith-that-abrogates-the-ten-forbidden-breastfeedings-by-five': '/posts/abrogation-of-quranic-verses-understanding-the-ten-and-five-breastfeedings-hadith',
  '/posts/these-two-are-magicians': '/posts/abu-amr-ibn-al-ala-did-he-challenge-the-quran',
  '/posts/deception-no-5-muhammad-and-abu-hurairah-uncover-the-abdomen-and-kiss-the-navel': '/posts/abu-hurairah-kissing-al-hasans-stomach-hadith-explained',
  '/posts/2026-projects': '/posts/additional-notes-on-prophet-muhammad-in-bible',
  '/posts/notes-on-prophet-muhammad-in-bible': '/posts/additional-notes-on-prophet-muhammad-in-bible',
  '/posts/breastfeeding-an-adult-between-christianity-and-islam': '/posts/adult-breastfeeding-in-islam-the-case-of-salim-the-prohibition-of-adoption-and-the-christian-double-standard',
  '/posts/ahad-vs-wahid': '/posts/ahad-vs-wahidواحد-vs-أحد-the-arabic-word-that-proves-gods-absolute-oneness-in-surah-al-ikhlas',
  '/posts/final-academic-response-1351212802366242877': '/posts/aisha-marriage-age-historical-evidence-scholarly-sources-refutation',
  '/posts/marriage-with-aisha': '/posts/aisha-marriage-age-historical-evidence-scholarly-sources-refutation',
  '/posts/aishas-jealousy-made-her-wish-to-be-stung-by-a-scorpion-or-a-snake': '/posts/aishas-jealousy-and-love-for-the-prophet-صلى-الله-عليه-وسلم-the-camel-incident-explained',
  '/posts/al-andalus-before-and-after-the-islamic-conquest': '/posts/al-andalus-islamic-civilization-and-the-liberation-from-visigothic-tyranny',
  '/posts/al-buraq': '/posts/al-buraq-and-the-bible-refuting-christian-claims-about-mythical-creatures-in-islam',
  '/posts/shocking-facts-about-the-fatimid-caliph-called-al-hakim-bi-amr-allah-who-persecuted-christians': '/posts/al-hakim-bi-amr-allah-the-fatimid-caliph-who-persecuted-christians-was-not-muslim-his-mother-was-christian-and-he-claimed-to-be-god',
  '/posts/holy-land-belongs-to-the-jews': '/posts/al-maidah-21-and-the-holy-land-the-quran-does-not-give-the-land-to-the-jews-it-gives-it-to-the-righteous-muslims',
  '/posts/the-doubt-about-al-zuhris-statement-we-were-informed-that-he-had-recited-a-lot-of-the-quran': '/posts/al-zuhris-weak-narration-debunked-no-the-quran-was-never-lost-or-incomplete',
  '/posts/syriac-borrows-the-name-god-from-arabic-according-to-scientific-and-archaeological-evidence': '/posts/allah-is-not-from-syriac-archaeological-proof-the-word-is-originally-arabic',
  '/posts/animal-rights-between-christianity-and-islam': '/posts/animal-rights-in-islam-vs-the-bible-dominion-versus-honor-a-comparative-study',
  '/posts/differences-in-quranic-manuscripts-advanced': '/posts/are-quranic-manuscript-differences-evidence-of-corruption-a-refutation-of-daniel-brubaker',
  '/posts/who-is-asiya-bint-muzahim': '/posts/asiya-bint-muzahim-identified-as-isis-nefert-of-egypt',
  '/posts/who-is-asiya-bint-muzahim-1325166212518383616': '/posts/asiya-bint-muzahim-is-isis-nefert-6-historical-proofs-that-match',
  '/posts/by-sawt-al-haqiqa-ig': '/posts/aw-rah-of-slave-women',
  '/posts/samarkand-manuscript': '/posts/bentaaurs-tashkent-quran-manuscript-forgery-exposed-concealed-corrections-false-provenance',
  '/posts/slave-as-second-wife-in-christianity': '/posts/biblical-concubinage-was-not-normal-marriage-jewish-sources-expose-the-claim',
  '/posts/blasphemy-and-atonement-in-christianity': '/posts/blasphemy-and-takfir-in-christianity-from-the-bible-the-fathers-the-synaxarium-and-coptic-hymns',
  '/posts/useless-try-to-debunk-me-on-breastfeeding-in-islam-topic': '/posts/breastfeeding-from-the-semen-of-a-stallion-refuting-the-polemical-misreading-of-sahih-muslim-and-the-hadith-of-aflah-ibn-abi-al-qays',
  '/posts/the-suspicion-of-the-prophets-order-to-burn-the-house-of-the-jewish-suwailem': '/posts/burning-the-house-of-jew-suwaylim-a-weak-hadith-refuted',
  '/posts/camels-were-created-from-devils': '/posts/camels-created-from-devils-what-the-hadith-actually-means-according-to-islamic-scholars',
  '/posts/with-the-eyes': '/posts/can-believers-see-allah-resolving-the-alleged-contradiction-between-quran-75-22-83-15-and-6-103',
  '/posts/debunking-the-myth-that-life-originated-by-chance-through-serendipitous-chemical-reactions-and-res': '/posts/can-life-arise-by-chance-debunking-abiogenesis-through-logic-and-cell-biology',
  '/posts/rules-for-disciplining-children-in-the-bible': '/posts/child-discipline-in-the-book-of-sirach-and-the-islamic-principle-of-mercy',
  '/posts/atonement-in-christianity': '/posts/christian-takfir-excommunication-damnation-of-non-christians-and-apostasy-penalties-in-christian-theology',
  '/posts/circumambulating-the-kaaba': '/posts/circumambulating-the-kaaba-is-paganism-the-bible-answers',
  '/posts/no-witness-to-revelation': '/posts/companions-witnessed-the-prophet-صلى-الله-عليه-وسلم-receiving-revelation-refuting-the-no-witnesses-argument',
  '/posts/pharaohs-drowning-and-death': '/posts/contradiction-in-the-quran-regarding-pharaohs-drowning',
  '/posts/cutting-people-with-knives-and-axes-sawing-them-apart-tearing-them-apart-with-threshing-machin-1327293582695993344': '/posts/davids-massacre-in-2-samuel-12-2931-old-bible-translations-vs-modern-changes',
  '/posts/deficient-in-religion': '/posts/deficient-in-mind-and-religion-hadith-meaning-context-and-full-refutation',
  '/posts/women-are-deficient-in-religio': '/posts/deficient-in-mind-and-religion-hadith-meaning-context-and-full-refutation',
  '/posts/killing-children-of-apostates-in-the-bible': '/posts/deuteronomy-13-the-bible-commands-the-total-destruction-of-apostate-cities-including-children',
  '/posts/dt-33-2': '/posts/deuteronomy-33-prophecy-of-muhammad-صلى-الله-عليه-وسلم-biblical-text-hebrew-analysis-and-linguistic-evidence',
  '/posts/prophecy-in-deuteronomy-332': '/posts/deuteronomy-33-prophecy-of-muhammad-صلى-الله-عليه-وسلم-biblical-text-hebrew-analysis-and-linguistic-evidence',
  '/posts/dhul-khulasa-ghazwa': '/posts/dhul-khulasa-ghazwa-dhul-khulasa-hadith-explained-did-the-prophet-order-killing',
  '/posts/the-blind-companion-killed-his-wife-or-female-slave-when-she-insulted-the-prophet': '/posts/did-a-blind-companion-kill-his-wife-for-insulting-the-prophet-complete-hadith-refutation',
  '/posts/t-is-the-hadith-about-a-woman-drinking-the-urine-of-the-prophet-peace-an': '/posts/did-a-woman-drink-the-prophet-muhammads-urine-hadith-authenticity-explained',
  '/posts/response-to-the-lie-that-abdul-qadir-al-jilani-slept-in-aishas-lap': '/posts/did-abdul-qadir-al-jilani-breastfeed-from-aisha-refutation',
  '/posts/the-best-of-creators': '/posts/did-abdullah-ibn-abi-sarh-corrupt-the-quran-refuting-the-best-of-creators-doubt',
  '/posts/his-burning-of-al-fujaah-al-salami': '/posts/did-abu-bakr-burn-al-fujaa-peacefully-the-narrations-are-weak-and-the-context-is-misrepresented',
  '/posts/al-anbiya-98-qiraats-difference': '/posts/did-aisha-and-the-companions-recite-hadhab-jahannam-refuting-a-false-quranic-variant-claim-surah-al-anbiya-verse-98',
  '/posts/deception-no-4-why-is-hassans-character-similar-to-the-character-of-the-messenger-of-god': '/posts/did-al-hasan-resemble-prophet-muhammad-in-physical-strength',
  '/posts/how-did-christianity-spread': '/posts/did-christianity-spread-by-the-sword-a-historical-indictment',
  '/posts/what-did-the-companions-do-during-prayer': '/posts/did-companions-lust-during-prayer-the-hadith-explained',
  '/posts/abubakr-and-umar-are-among-the-doomed': '/posts/did-ibn-abbas-permit-mutah-why-the-report-refers-to-hajj-tamattu-not-temporary-marriage',
  '/posts/did-abdullah-bin-masoud-deny-the-two-muawwidhat': '/posts/did-ibn-masud-deny-surah-al-falaq-and-surah-an-nas',
  '/posts/ibn-omars-suspicion-and-sexual-harassment-in-islam-slavery': '/posts/did-ibn-umar-touch-female-slaves-in-markets-a-hadith-critical-examination-of-all-relevant-narrations',
  '/posts/deception-no-2-a-muslim-man-would-marry-one-of-sahaba-so-that-she-would-spend-on-him': '/posts/did-islam-allow-muslim-men-to-marry-prostitutes-for-money',
  '/posts/arian-heresy-argument': '/posts/did-islam-borrow-from-the-ebionites-and-arians-the-jewish-christian-myth-refuted',
  '/posts/sirat-was-borrowed-from-zoroastrianism-and-the-response-to-the-orientalist-missionary-tsdal': '/posts/did-islam-borrow-the-concept-of-the-sirāṭ-from-zoroastrianism-a-refutation',
  '/posts/islam-spread-by-war': '/posts/did-islam-spread-by-the-sword-what-historians-actually-say',
  '/posts/did-jacob-wrestle-with-the-god-of-the-christians-or-did-he-wrestle-with-a-human-being': '/posts/did-jacob-wrestle-with-the-god-of-the-christians-or-with-a-human-being',
  '/posts/the-response-to-christs-claim-is-that-god-creates-from-clay-the-shape-of-a-bird-and-it-becomes-a-b': '/posts/did-jesus-creating-a-bird-from-clay-prove-he-is-god-quran-gospel-scholars-answer',
  '/posts/john-8-58': '/posts/did-jesus-ever-say-i-am-god-the-ego-eimi-and-yahweh-argument-destroyed',
  '/posts/did-joshua-destroy-the-walls-of-jericho': '/posts/did-joshua-destroy-the-walls-of-jericho-the-archaeological-evidence-against-the-book-of-joshua',
  '/posts/khalid-bin-al-walid-may-allah-be-pleased-with-him-was-a-cannibal-who': '/posts/did-khalid-ibn-al-walid-commit-cannibalism-refuting-the-slander-full-isnad-analysis-biblical-counter-evidence',
  '/posts/monkey-adultery': '/posts/did-monkeys-stone-for-zina-refuting-the-sahih-al-bukhari-objection',
  '/posts/contradiction-in-the-quran-as-it-mentions-different-statements-about-the-fire-that-moses-peace-be': '/posts/did-moses-say-different-things-about-the-fire-refuting-the-quran-contradiction-claim',
  '/posts/doubt-about-moses-peace-be-upon-him-throwing-the-tablets': '/posts/did-moses-throwing-the-tablets-disrespect-gods-word-al-araf-150-explained-with-tafsir-bible',
  '/posts/responding-to-the-suspicion-that-embryology-in-the-quran-is-borrowed-from-aristotle-and-hippocrates': '/posts/did-muhammad-copy-embryology-from-greek-science-refuting-the-aristotle-and-hippocrates-claim',
  '/posts/responding-to-the-allegation-did-the-quran-steal-the-word-allah-from-elohim-in-the-jewish-heri': '/posts/did-muslims-steal-allah-from-elohim-a-linguistic-refutation',
  '/posts/orientalists-on-quran': '/posts/did-orientalists-acknowledge-the-quran-was-preserved-what-the-sources-say',
  '/posts/orientalists-on-the-preservation-of-quran': '/posts/did-orientalists-acknowledge-the-quran-was-preserved-what-the-sources-say',
  '/posts/abraham-lied': '/posts/did-prophet-abraham-commit-shirk-or-doubt-refuting-quranic-misconceptions-about-ibrahim-صلى-الله-عليه-وسلم',
  '/posts/is-surat-al-fil-borrowed-from-the-poet-rubah-ibn-al-ajaj': '/posts/did-prophet-muhammad-borrow-surah-al-fil-refuting-the-rubah-ibn-al-ajjaj-claim',
  '/posts/muslim-prayer-is-taken-from-the-sumerian-civilization': '/posts/did-prophet-muhammad-copy-prayer-from-sumerians-a-complete-refutation',
  '/posts/deception-no-20-muhammads-denial-of-the-companions-you-do-not-know-what-they-innovated-after-y': '/posts/did-prophet-muhammad-disown-his-companions-hadith-explained',
  '/posts/deception-no-12-the-companions-bad-behavior-towards-the-prophet-may-god-bless-him-and-grant-him': '/posts/did-prophet-muhammad-distribute-spoils-unfairly-at-hunayn',
  '/posts/a-chain-by-chain-analysis-of-the-eight-narrations-used-to-claim-the-prophet-desired-zainab-bint-jahsh-with-the-positions-of-classical-and-modern-scholars': '/posts/did-prophet-muhammad-lust-after-zainab-a-hadith-by-hadith-investigation',
  '/posts/deception-no-21-some-of-my-friends-do-not-see-me-after-i-leave-them': '/posts/did-prophet-muhammad-say-some-companions-would-not-see-him-again',
  '/posts/response-to-the-allegation-that-the-prophet-defecated-and-ate-without-washing-his-hands-or-touching': '/posts/did-prophet-muhammad-صلى-الله-عليه-وسلم-eat-with-unclean-hands-full-refutation-of-the-christian-polemic',
  '/posts/angels-do-not-enter-the-house-of-the-messenger-of-islam': '/posts/did-prophet-muhammad-صلى-الله-عليه-وسلم-keep-urine-under-his-bed-refuting-the-angel-objection',
  '/posts/bukhari-6982-suicide': '/posts/did-prophet-muhammad-صلى-الله-عليه-وسلم-try-to-commit-suicide-refuting-the-weak-bukhari-addition-az-zuhris-idraj',
  '/posts/myth-of-the-creation-of-adam-and-how-satan-entered-through-his-mouth-and-exited-through-his-anus': '/posts/did-satan-enter-adams-body-refuting-a-weak-israiliyyat-narration-misused-against-islam',
  '/posts/scholars-differed-in-interpreting-the-holy-quran': '/posts/did-scholars-disagree-on-the-entire-quran-the-scope-of-tafsir-differences-explained',
  '/posts/bukhari-2592': '/posts/did-scholars-prefer-keeping-slaves-over-freedom-context-refutes',
  '/posts/sahih-al-bukhari-2-ring-sheytan': '/posts/did-the-bell-hadith-prove-muhammad-received-revelation-from-satan',
  '/posts/deception-no-16-i-do-not-know-anything-today-of-what-we-were-like-during-the-time-of-the-messeng': '/posts/did-the-companions-change-the-sunnah-after-prophet-muhammad',
  '/posts/deception-no-3-the-companions-come-to-arafat-and-their-penises-drip-with-semen': '/posts/did-the-companions-go-to-arafat-while-dripping-with-semen-hadith-explained',
  '/posts/the-response-to-the-lie-that-the-prophet-peace-and-blessings-be-upon-him-quoted-from-the-monk-bahi': '/posts/did-the-monk-bahira-teach-the-prophet-صلى-الله-عليه-وسلم-the-quran-6-historical-proofs-syriac-forgeries-catholic-encyclopedia-answer',
  '/posts/she-died-so-i-slept-with-her': '/posts/did-the-prophet-lie-with-fatima-bint-asad-in-her-grave-linguistic-and-hadith-refutation-of-the-christian-allegation',
  '/posts/bani-mustaliq': '/posts/did-the-prophet-muhammad-attack-peaceful-people-the-raid-on-banu-al-mustaliq-explained',
  '/posts/historical-evidence-of-the-messenger-of-god-may-god-bless-him-and-grant-him-peace': '/posts/did-the-prophet-muhammad-really-exist-historical-proof-from-coins-inscriptions-and-non-muslim-chronicles',
  '/posts/sahih-muslim-1668a': '/posts/did-the-prophet-oppose-freeing-slaves-the-deathbed-hadith-explained',
  '/posts/reply-to-the-doubt-the-messenger-of-islam-prayed-without-purification': '/posts/did-the-prophet-pray-without-ablution-the-hadith-evidence-examined',
  '/posts/black-people-steal-when-hungry-is-there-any-racism-in-islam': '/posts/did-the-prophet-say-black-people-steal-when-hungry-a-hadith-refutation',
  '/posts/spat-in-his-garment': '/posts/did-the-prophet-spit-on-his-clothes-the-prayer-context-explained',
  '/posts/touching-a-womans-chest-breast': '/posts/did-the-prophet-touch-a-womans-chest-a-weak-hadith-exposed',
  '/posts/explanation': '/posts/did-the-prophet-violate-quran-2-222-the-meaning-of-mubashara-during-menstruation-explained',
  '/posts/the-prophet-saw-cursing-a-lot': '/posts/did-the-prophet-صلى-الله-عليه-وسلم-curse-an-orphan-girl-sahih-muslim-2603-explained',
  '/posts/bukhari-2771': '/posts/did-the-prophet-صلى-الله-عليه-وسلم-intend-to-kill-the-man-accused-with-mariyah',
  '/posts/understanding-the-hadith-of-the-man-accused-with-mariyah-bukhari-2771': '/posts/did-the-prophet-صلى-الله-عليه-وسلم-intend-to-kill-the-man-accused-with-mariyah',
  '/posts/refuting-the-claim-that-the-prophet-peace-and-blessings-be-upon-him-borrowed-from-jabr-and-yasar': '/posts/did-the-prophet-صلى-الله-عليه-وسلم-learn-from-two-christian-slaves-the-jabr-yasar-accusation-refuted',
  '/posts/killing-of-kinana-bin-al-rabi-bin-abi-al-haqiq': '/posts/did-the-prophet-صلى-الله-عليه-وسلم-order-the-torture-of-kinanah-ibn-al-rabi-a-full-isnad-refutation-of-the-khaybar-slander',
  '/posts/wrestled-with-satan': '/posts/did-the-prophet-صلى-الله-عليه-وسلم-really-wrestle-the-devil-refuting-the-missionary-doubt-with-their-own-bible',
  '/posts/update-2026-1490037128745189496': '/posts/did-the-prophet-صلى-الله-عليه-وسلم-say-anakta-hā-the-maiz-hadith-arabic-usage-and-legal-clarity',
  '/posts/anekatah': '/posts/did-the-prophet-صلى-الله-عليه-وسلم-say-anakta-hā-the-maiz-hadith-arabic-usage-and-legal-clarity',
  '/posts/existence-of-statues-or-pictures-of-jesus-son-of-mary-and-his-mother-in-the-kaaba': '/posts/did-the-prophet-صلى-الله-عليه-وسلم-spare-the-image-of-mary-jesus-in-the-kaaba-al-azraqis-narrations-examined-with-11-authentic-hadiths',
  '/posts/the-response-to-those-who-denied-the-incident-of-the-splitting-of-the-prophets-chest-may-god-bless': '/posts/did-the-prophets-chest-split-open-miracles-and-modern-science',
  '/posts/the-quran-and-umayyah-ibn-abi-al-salt': '/posts/did-the-quran-borrow-from-umayyah-ibn-abi-al-salt-a-complete-refutation',
  '/posts/is-the-story-of-luqman-s-advice-to-his-son-transferred': '/posts/did-the-quran-borrow-luqmans-wisdom-from-ahiqar-full-refutation-of-the-claim',
  '/posts/the-quran-borrowed-the-story-of-solomon-and-the-hoopoe-from-targum-esther-ii': '/posts/did-the-quran-borrow-solomons-hoopoe-story-from-targum-sheni',
  '/posts/contradiction-in-the-quran-in-its-mention-of-the-words-of-god-almighty-to-moses-peace-be-upon-him': '/posts/did-the-quran-contradict-itself-about-allah-speaking-to-moses',
  '/posts/story-of-abraham-and-his-father-in-the-quran-was-quoted-from-the-haggadah': '/posts/did-the-quran-copy-abrahams-story-from-the-haggadah-a-complete-refutation-with-historical-evidence',
  '/posts/blowing-up-the-talmudic-traditions-in-the-quran': '/posts/did-the-quran-copy-the-talmud-a-complete-refutation-of-the-plagiarism-claim',
  '/posts/doubts-and-responses-to-allegations-of-distortion-of-the-holy-quran': '/posts/did-the-quran-get-distorted-scholarly-refutations-to-8-major-claims-al-hajjaj-ibn-masoud-surat-al-noorayn-more',
  '/posts/sunset': '/posts/did-the-quran-say-the-sun-literally-sets-in-a-muddy-spring-quran-18-86-explained',
  '/posts/the-anomalous-readings-of-ubayd-ikrimah-mujahid-saeed-alqamah-hattan-al-amash': '/posts/do-anomalous-tabiin-readings-disprove-the-qurans-preservation-chain-analysis-birmingham-manuscript-orientalist-testimony',
  '/posts/response-to-christans-the-cross-do-we-honor-it-or-worship-it': '/posts/do-christians-worship-the-cross-cross-veneration-and-the-kaaba-comparison-examined',
  '/posts/update-1369578720981155840': '/posts/do-muslims-worship-the-kaaba-the-qibla-accusation-refuted-with-christian-biblical-evidence',
  '/posts/does-god-have-teeth-and-a-palate': '/posts/does-allah-have-a-uvula-and-molars-hadith-chain-analysis',
  '/posts/does-alllahhave-teeth-and-a-palate': '/posts/does-allah-have-a-uvula-and-molars-hadith-chain-analysis',
  '/posts/allah-swt-misguides': '/posts/does-allah-misguide-people-quran-16-93-explained-with-tafsir-and-human-free-will',
  '/posts/response-to-a-slander-regarding-the-verse-and-what-is-that-in-your-right-hand-o-moses': '/posts/does-allahs-question-to-moses-prove-limited-knowledge-taha-20-17-explained',
  '/posts/the-meaning-of-as-samad': '/posts/does-as-samad-prove-the-trinity-zakaria-botros-refuted-with-hebrew-and-arabic',
  '/posts/the-response-to-the-doubt-how-does-god-create-man-and-then-marvel-at-his-disbelief-and-say-how-un': '/posts/does-god-marvel-at-human-disbelief-quran-80-17-explained',
  '/posts/a-stupid-suspicion-about-the-hanafi-school-of-thought-the-religion-of-the-prophet-abraham-peace-be': '/posts/does-hanif-mean-pagan-refuting-the-christian-objection-against-abrahams-religion',
  '/posts/book-of-hosea': '/posts/does-hosea-9-6-mention-muhammad-by-name-the-hebrew-word-machmas-explained',
  '/posts/the-name-of-muhammad-in-hosea-96': '/posts/does-hosea-9-6-mention-muhammad-by-name-the-hebrew-word-machmas-explained',
  '/posts/does-isaiah-53-talk-about-the-crucifixion-and-resurrection-of-christ': '/posts/does-isaiah-53-prophesy-jesus-hebrew-and-septuagint-evidence-against-the-christian-claim',
  '/posts/deception-no-31-omar-the-companions-and-the-muslims-curse-the-infidels': '/posts/does-islam-allow-cursing-disbelievers',
  '/posts/the-lie-that-islam-attributes-the-child-of-adultery-to-the-husband': '/posts/does-islam-attribute-adultery-children-to-the-husband-refuting-the-child-belongs-to-the-bed',
  '/posts/inappropriate-words': '/posts/does-islam-order-the-insulting-of-non-muslims-contextualizing-the-harsh-prophetic-hadiths',
  '/posts/title-does-islam-order-the-insulting-of-non-muslims-contextualizing-the-harsh-prophetic-hadiths': '/posts/does-islam-order-the-insulting-of-non-muslims-contextualizing-the-harsh-prophetic-hadiths',
  '/posts/a-response-to-the-accursed-enemies-of-religion-who-said-that-islam-permits-bestiality': '/posts/does-islam-permit-bestiality-classical-fiqh-refutation-of-a-false-claim',
  '/posts/bukhari-304-dumb-women': '/posts/does-islam-say-women-are-stupid-refuting-the-deficient-in-intelligence-hadith',
  '/posts/fever-for-sins': '/posts/does-islam-teach-that-fever-expiates-all-sins-including-major-ones-a-clarification-of-the-hadith',
  '/posts/does-the-quran-acknowledge-jacobs-struggle-with-god': '/posts/does-israel-mean-wrestling-with-god-hebrew-lexicon-islamic-tafsir-rabbi-rashi-father-tadros-answer',
  '/posts/and-now-father-glorify-me-in-your-own-presence-with-the-glory-that-was-mine-john-17-5-does-this': '/posts/does-john-17-5-indicate-the-divinity-of-christ',
  '/posts/a-description-of-the-chests-of-the-houris': '/posts/does-kawāʿib-atrāban-mean-sexualized-maidens-refuting-the-surah-an-naba-78-33-claim',
  '/posts/contradiction-in-the-quran-regarding-swearing-by-places-and-times': '/posts/does-la-uqsimu-contradict-quranic-oaths',
  '/posts/does-the-title-lord-mean-the-divinity-of-christ-kyrios-and-the-specifications-of-the-messiah-a': '/posts/does-lord-prove-jesus-is-god-kyrios-explained-from-christian-sources',
  '/posts/nikkah-means-sex': '/posts/does-nikāḥ-mean-sex-in-the-quran-refuting-the-claim-with-arabic-and-quranic-usage',
  '/posts/surah-ahzab-53': '/posts/does-quran-33-53-prove-the-prophet-made-up-revelation',
  '/posts/trinity-exist-in-islam': '/posts/does-the-christian-trinity-exist-in-islam-a-complete-refutation',
  '/posts/bukhari-4814': '/posts/does-the-coccyx-bone-decay-bukhari-hadith-on-resurrection',
  '/posts/jesus-was-not-touched-by-satan': '/posts/does-the-hadith-of-satans-stab-prove-jesus-is-divine-a-full-refutation',
  '/posts/the-moon-a-light-in-them': '/posts/does-the-moon-light-the-seven-heavens-quran-71-15-16-explained',
  '/posts/the-response-to-the-doubt-and-he-made-the-moon-a-light-in-them': '/posts/does-the-moon-light-up-all-seven-heavens-surah-nuh-71-1516-explained-with-tafsir-arabic-grammar',
  '/posts/proof-jesus-is-god-in-quran': '/posts/does-the-quran-call-jesus-god-refuting-christian-proof-texts',
  '/posts/27-linguistic-errors-in-the-holy-quran': '/posts/does-the-quran-have-arabic-grammar-mistakes-every-objection-answered',
  '/posts/word-of-god-and-spirit-of-god': '/posts/does-the-quran-prove-jesus-is-god-the-word-of-god-missionary-deception-exposed',
  '/posts/response-to-the-doubt-mount-qaf-that-surrounds-the-earth': '/posts/does-the-quran-teach-a-mount-qaf-surrounds-the-earth-refuting-the-myth',
  '/posts/hadiths-suggesting-distortion-of-the-quran-and-the-response-to-them': '/posts/doubts-about-quranic-preservation-ten-objections-and-their-video-refutations',
  '/posts/1st-doubt': '/posts/doubts-regarding-prophet-marriage-with-safiyyah-bint-huyayy',
  '/posts/elijah-is-god-christians': '/posts/elijah-performed-the-same-miracles-as-jesus-why-christians-dont-worship-elijah',
  '/posts/proof-of-the-invalidity-of-using-the-word-elohim-to-prove-the-trinity': '/posts/elohim-is-not-evidence-for-the-trinity-a-linguistic-and-scriptural-refutation',
  '/posts/distortion-of-the-text-of-ephesians-3-9-who-created-all-things-through-jesus-christ': '/posts/ephesians-3-9-exposed-how-through-jesus-christ-was-added-to-the-bible',
  '/posts/immortal-boys-youth': '/posts/eternal-youths-in-paradise-explained-refuting-the-false-claim-about-quran-76-19',
  '/posts/even-if-he-committed-adultery-and-even-if-he-stole': '/posts/even-if-he-committed-adultery-and-even-if-he-stole-does-islam-permit-major-sins',
  '/posts/obscene-and-indecent-sexual-paragraphs-in-bible': '/posts/explicit-and-obscene-language-in-the-bible',
  '/posts/false-gospel-prophecies': '/posts/false-prophecies-in-the-new-testament-six-cases-where-the-gospel-writers-fabricated-distorted-or-misapplied-old-testament-texts',
  '/posts/filth-is-the-hallmark-of-faith-in-christianity': '/posts/filth-as-holiness-the-christian-tradition-of-rejecting-cleanliness-and-its-contrast-with-islamic-purity',
  '/posts/deception-no-24-after-me-there-will-be-imams-who-will-not-be-guided-by-my-guidance-or-my-sunnah': '/posts/future-corrupt-rulers-in-sahih-muslim-hadith-explained',
  '/posts/galatians-1-8': '/posts/galatians-1-69-paul-was-fighting-christians-not-muslims',
  '/posts/geckos-are-incapable-of-blowing': '/posts/gecko-blowing-on-fire-hadith-atheist-objection-refuted',
  '/posts/contradictions-in-the-story-of-the-rape-of-dinah-the-daughter-of-our-master-jacob-in-the-book-of-g': '/posts/genesis-34-and-the-rape-of-dinah-internal-contradictions-proving-later-insertion-into-the-biblical-text',
  '/posts/belief-in-god-almighty-between-islam-and-christianity': '/posts/god-in-islam-and-christianity-tawhid-the-deleted-trinity-verse-and-twenty-unworthy-biblical',
  '/posts/embroyoloy': '/posts/hadith-of-42-nights-embryology-sex-differentiation-and-organ-formation-explained',
  '/posts/a-collection-of-historical-and-geographical-errors-in-the-gospel-of-mark-quote-from-the-book-of-sai': '/posts/historical-and-geographical-errors-in-the-gospel-of-mark-ninehams-evidence-explained',
  '/posts/has-science-proven-the-impossibility-of-diversification-from-two-pairs': '/posts/hla-gene-diversity-and-adam-eve-does-science-disprove-a-two-person-bottleneck',
  '/posts/abu-bakrs-method-in-collecting-the-quran': '/posts/how-abu-bakr-collected-the-quran-the-strict-method-that-preserved-the-mushaf',
  '/posts/the-response-to-the-doubt-about-how-god-created-every-animal-and-every-living-thing-from-water-whil': '/posts/how-can-allah-create-everything-from-water-if-jinn-were-created-from-fire-a-complete-response',
  '/posts/the-spread-of-christianity-through-violence-in-egypt': '/posts/how-christianity-was-forced-on-egypt-temple-destruction-and-religious-coercion',
  '/posts/the-response-to-the-doubt-about-the-ant-conversation-with-solomon': '/posts/how-did-the-ant-speak-in-surah-an-naml-science-arabic-linguistics-biblical-parallels',
  '/posts/response-to-anba-takla-website-how-does-god-die-as-you-say': '/posts/how-does-god-die-the-internal-contradiction-in-christian-atonement-theology',
  '/posts/angels-in-surah-al-imran-mary': '/posts/how-many-angels-gave-mary-glad-tidings-refuting-the-quran-contradiction-claim-2',
  '/posts/the-contradiction-in-the-number-of-angels-in-the-battle-of-badr': '/posts/how-many-angels-were-at-badr-resolving-the-1000-vs-3000-vs-5000-doubt-quran-tafsir-bible',
  '/posts/christians-under-muslim-rule-a-legacy-of-fair-treatment': '/posts/how-muslims-treated-christians-historical-sources-on-islamic-protection-religious-freedom-and-rescue-from-byzantine-persecution',
  '/posts/a-distortion-to-obliterate-the-good-tidings-on-the-tongue-of-christ': '/posts/how-scribes-removed-muhammads-prophecies-from-the-gospel-of-john',
  '/posts/john-7-52-the-prophet-of-end-times': '/posts/how-scribes-removed-muhammads-prophecies-from-the-gospel-of-john',
  '/posts/distortions-in-gospel-of-john-to-obliterate-the-prophecy-on-the-tongue-of-jesus': '/posts/how-scribes-removed-muhammads-prophecies-from-the-gospel-of-john',
  '/posts/doubts-about-the-compilation-of-the-holy-quran': '/posts/how-was-the-quran-compiled-dots-diacritics-the-two-collections-doubts-answered',
  '/posts/falsifying-the-genetic-similarity-between-humans-and-apes': '/posts/human-ape-dna-similarity-refuted-the-988-genetic-similarity-claim-examined',
  '/posts/response-to-anba-takla-website-the-issue-of-i-do-nothing-of-myself': '/posts/i-do-nothing-of-myself-does-john-8-28-prove-christs-subordination-to-the-father',
  '/posts/distortion-of-the-word-samad-in-the-editions-of-ibn-kathirs-interpretation-or-vice-versa': '/posts/ibn-kathir-and-samad-refuting-the-claim-that-allahs-name-came-from-an-idol',
  '/posts/abraham-lied-1325421805514784820': '/posts/ibrahim-only-told-three-lies-what-did-the-prophet-صلى-الله-عليه-وسلم-mean-al-nawawi-ibn-al-jawzi-al-razi-explained',
  '/posts/if-jesus-is-god-because-he-forgave-sins-then-let-the-christian-worship-the-jewish-priest-because-he': '/posts/if-jesus-forgave-sins-does-that-prove-he-is-god-a-biblical-refutation',
  '/posts/a-day-with-god-a-thousand-years-or-50-thousand-years': '/posts/is-a-day-with-allah-1000-or-50000-years-refuting-the-quran-contradiction-claim',
  '/posts/a-womans-voice-is-shameful': '/posts/is-a-womans-voice-awrah-what-islam-actually-says-vs-what-the-bible-says',
  '/posts/moon-god': '/posts/is-allah-a-moon-god-the-claim-debunked-and-why-yahweh-has-a-bigger-problem',
  '/posts/the-word-bism-is-a-syriac-script-and-not-an-arabic-one': '/posts/is-bismillah-syriac-refuting-the-script-origin-claim',
  '/posts/is-it-true-in-christianity-that-god-loved-the-world-so-much-that-he-gave-his-only-son-and-love-yo': '/posts/is-christian-love-unconditional-a-review-of-love-hatred-and-punishment-in-the-bible',
  '/posts/david-is-also-the-christ-the-son-of-god-the-forgotten-fourth-divine-person': '/posts/is-david-also-the-christ-and-son-of-god-a-biblical-challenge-to-christian-title-based-divinity-claims',
  '/posts/is-christ-like-adam': '/posts/is-jesus-like-adam-refuting-8-christian-claims-about-the-divinity-of-christ-using-the-quran',
  '/posts/s-jizyah-usury-refuting-the-quranic-contradiction-claim': '/posts/is-jizyah-usury-refuting-the-quranic-contradiction-claim',
  '/posts/is-the-prophet-descended-from-the-prostitute-and-fallen-grandmother-of-jesus-tamar': '/posts/is-prophet-muhammad-صلى-الله-عليه-وسلم-descended-from-tamar-refuting-the-zerah-genealogy-claim',
  '/posts/response-to-christan-lies': '/posts/is-prophet-muhammads-lineage-pure-responding-to-christian-missionary-claims-with-classical-evidence',
  '/posts/response-to-christan-lies-on-geneology': '/posts/is-prophet-muhammads-lineage-pure-responding-to-christian-missionary-claims-with-classical-evidence',
  '/posts/response-to-christan-lies-on-geneology-of-prophet': '/posts/is-prophet-muhammads-lineage-pure-responding-to-christian-missionary-claims-with-classical-evidence',
  '/posts/desire-of-nations': '/posts/is-the-desire-of-all-nations-in-haggai-2-7-a-prophecy-about-muhammad-the-hebrew-hmd-explained',
  '/posts/hadith-about-the-age-of-flies': '/posts/is-the-hadith-about-the-flys-lifespan-being-40-nights-authentic-full-isnad-analysis-scientific-proof',
  '/posts/is-the-cupping-on-empty-stomach-hadith-authentic': '/posts/is-the-hijama-on-an-empty-stomach-hadith-authentic-chain-analysis-and-scholarly-verdicts',
  '/posts/is-the-word-waqi-distorted-in-the-quran-why-is-there-no-extension-of-the-alif-in-some-words-in': '/posts/is-the-word-wāqi-distorted-in-the-quran-the-truth-about-alif-in-ancient-manuscripts',
  '/posts/surah-nisa-34-domestic-abuse-quran-434': '/posts/islam-and-wife-beating-classical-scholars-on-quran-4-34-and-its-strict-limits',
  '/posts/sunan-ibn-majah-3986': '/posts/islam-will-return-strange-hadith-on-the-end-times',
  '/posts/what-has-islam-given-to-the-world': '/posts/islamic-civilization-and-science-what-history-actually-records',
  '/posts/if-a-morsel-of-food-falls-from-one-of-you-let-him-pick-it-up': '/posts/islamic-eating-etiquette-vs-the-gospel-rejection-of-handwashing-a-comparative-study',
  '/posts/responding-to-the-allegation-of-sex-in-heritage-books': '/posts/islamic-heritage-texts-and-sex-refuting-secularist-distortions',
  '/posts/captives-of-awtas': '/posts/islamic-rules-of-war-captives-the-rape-accusation-a-complete-refutation',
  '/posts/response-to-the-claim-that-positive-laws-are-better-than-the-provisions-of-islamic-law': '/posts/islamic-sharia-vs-positive-law-a-comprehensive-refutation-of-the-claim-that-man-made-laws-are-superior',
  '/posts/quote-from-the-book-of-job-stages-of-embryonic-development-from-ancient-peoples-cultures': '/posts/job-10-10-and-the-ancient-error-of-embryology-the-bible-reflects-pre-scientific-culture',
  '/posts/in-pictures-pope-kyrollos-vi-and-the-coptic-church-distort-the-bible-to-support-the-idea': '/posts/john-17-3-how-pope-kyrollos-vi-changed-and-to-with-to-fabricate-proof-for-the-divinity-of-christ',
  '/posts/reply-to-anba-takla-website-the-meaning-of-i-ascend-to-my-father-and-my-god': '/posts/john-20-17-my-father-and-your-father-my-god-and-your-god',
  '/posts/john-3-13': '/posts/john-3-13-who-is-in-heaven-a-divinity-proof-text-absent-from-the-two-oldest-papyri-sinaiticus-and-vaticanus',
  '/posts/the-story-of-the-angel-in-the-sinaiticus-manuscript-and-the-papal-lie-in-response-to-pope-shenouda': '/posts/john-5-34-and-the-angel-at-bethesda-missing-from-the-oldest-bible-manuscripts',
  '/posts/distortion-of-the-text-of-the-angel-of-blessing': '/posts/john-5-4-is-not-in-the-bible-manuscript-evidence-exposes-a-major-new-testament-distortion',
  '/posts/a-scribe-of-a-12th-century-new-testament-manuscript-added-a-proverb-to-the-text-because-it-fit-the-t': '/posts/john-7-4-a-12th-century-scribe-added-a-proverb-to-the-new-testament-text',
  '/posts/corruption-of-the-gospel-of-john-9-35': '/posts/john-9-35-son-of-man-or-son-of-god-how-one-word-change-turned-a-prophecy-verse-into-a-divinity-claim',
  '/posts/hajar-and-qatura-are-two-sides-of-the-same-coin': '/posts/keturah-is-hagar-jewish-tradition-rashi-the-targums-and-the-qumran-texts-confirm-abraham-had-only-two-wives',
  '/posts/the-problem-of-distorting-luke-1-28': '/posts/luke-1-28-blessed-are-you-among-women-a-later-scribal-addition-rejected-by-all-major-critical-editions',
  '/posts/the-distortion-of-luke-1-28-blessed-are-you-among-women': '/posts/luke-1-28-blessed-are-you-among-women-a-later-scribal-addition-rejected-by-all-major-critical-editions',
  '/posts/an-angel-from-heaven-appeared-to-him-to-strengthen-him': '/posts/luke-22-43-44-an-angel-strengthens-jesus-in-gethsemane-four-theological-problems-for-christianity',
  '/posts/distortion-of-the-text-of-luke-23-34-father-forgive-them-for-they-do-not-know-what-they-do': '/posts/luke-23-34-father-forgive-them-absent-from-oldest-manuscripts-and-bracketed-by-all-critical-editions',
  '/posts/the-distortion-of-luke-23-34-father-forgive-them': '/posts/luke-23-34-father-forgive-them-absent-from-oldest-manuscripts-and-bracketed-by-all-critical-editions',
  '/posts/the-distortion-of-luke-23-45-eclipse-or-darkness': '/posts/luke-23-45-eclipse-or-darkness-how-scribes-changed-the-original-greek-word-to-hide-an-astronomical-problem',
  '/posts/why-does-the-quran-describe-birds-as-speaking': '/posts/mantiq-al-tayr-did-the-quran-misuse-the-word-for-speech-the-linguistic-doubt-refuted',
  '/posts/marginalia': '/posts/marginalia-test',
  '/posts/mark-15-28-was-numbered-with-the-transgressors': '/posts/mark-15-28-was-added-by-scribes-missing-from-every-ancient-manuscript-and-every-critical-edition',
  '/posts/mar-7-16-mark-9-44-mark-9-46': '/posts/mark-7-16-and-mark-9-44-46-verses-deleted-from-the-oldest-manuscripts-and-absent-from-all-critical-editions',
  '/posts/distortion-of-the-text-of-matthew-17-21': '/posts/matthew-17-21-prayer-and-fasting-entire-verse-absent-from-sinaiticus-vaticanus-and-all-major-critical-editions',
  '/posts/when-an-accidental-error-is-more-serious-than-a-deliberate-distortion-the-problem-of-matthew-27-35': '/posts/matthew-27-35-prophecy-fulfillment-addition-absent-from-the-five-most-important-manuscripts-and-rejected-by-all-critical-editions',
  '/posts/8-messianic-prophecies-contained-in-the-gospel-of-matthew': '/posts/matthews-fabricated-messianic-prophecies-eight-old-testament-texts-ripped-out-of-context-and-misattributed-to-jesus',
  '/posts/melchizedek-or-jesus': '/posts/melchizedek-and-jesus-applying-christian-standards-of-divinity-to-a-biblical-figure',
  '/posts/the-miracle-of-the-unseen-in-the-hadiths-of-the-antichrist': '/posts/miracles-of-the-unseen-in-the-hadiths-of-the-antichrist-dajjal',
  '/posts/mirza-ghulams-kufr': '/posts/mirza-ghulam-qadianis-blasphemy-in-his-own-words-kufr-false-prophethood-and-the-qadiani-claim-exposed',
  '/posts/christians-doubt-about-the-stone-fleeing-in-moses-garment': '/posts/moses-and-the-stone-refuting-the-christian-objection-to-the-hadith-of-prophetic-modesty-and-the-children-of-israel',
  '/posts/deception-no-7-you-want-to-be-castrated-or-practice-temporary-marriage': '/posts/mutah-in-islam-was-temporary-marriage-later-forbidden',
  '/posts/reply-to-anba-takla-website-what-does-my-father-is-greater-than-i-mean': '/posts/my-father-is-greater-than-i-what-john-14-28-actually-means',
  '/posts/reply-to-takla-website-how-did-christ-say-while-on-the-cross-my-god-my-god-why-have-you-forsak': '/posts/my-god-why-have-you-forsaken-me-what-matthew-27-46-reveals',
  '/posts/as-for-my-cousin-he-violated-my-honor': '/posts/my-honor-was-violated-does-the-hadith-mean-the-prophet-صلى-الله-عليه-وسلم-was-assaulted',
  '/posts/a-clear-contradiction-in-hadith-with-quran': '/posts/no-contradiction-entering-paradise-by-deeds-and-allahs-mercy-in-quran-and-hadith',
  '/posts/a-muslim-shall-not-be-killed-for-killing-an-infidel': '/posts/no-muslim-killed-for-an-infidel-what-the-hadith-actually-means-and-what-critics-deliberately-ignore',
  '/posts/why-does-god-swear-by-his-creatures-and-not-by-his-divine-self': '/posts/oaths-in-the-quran-why-does-allah-swear-by-his-creation-the-eloquence-and-purpose-explained',
  '/posts/circumcision-between-paul-and-the-world-health-organization-and-the-rule-of-the-interest-of-the-huma': '/posts/paul-abolished-the-eternal-covenant-of-circumcision-against-gods-word-against-medical-science-and-against-christs-own-teachings',
  '/posts/paul-in-quran': '/posts/paul-is-not-mentioned-in-the-quran-refuting-the-christian-claim-that-surah-ya-sin-references-paul',
  '/posts/prophecies-of-the-end-time-b-prophet': '/posts/prophecies',
  '/posts/prophcies': '/posts/prophecies',
  '/posts/bukhari-7116': '/posts/prophecy-of-dhi-al-khalasa-idol-worshipped-again-in-history',
  '/posts/related-doubts': '/posts/prophet-may-god-bless-him-and-grant-him-peace-took-the-mother-of-the-believers-safiyyah-bint-huyayy-took-her-people-prisoner-and-fought-them-and-took-their-money',
  '/posts/bukhari-4428-poisoned': '/posts/prophet-muhammad-صلى-الله-عليه-وسلم-die-as-a-false-prophet-refuting-the-poison-and-aorta-arguments',
  '/posts/caravan-raid': '/posts/prophet-muhammads-caravan-raids-explained-defensive-warfare-not-offensive-aggression',
  '/posts/reply-to-the-text-the-lord-the-lord-said-the-end-of-the-illusion': '/posts/psalm-110-1-does-the-lord-said-to-my-lord-prove-jesus-is-god',
  '/posts/psalms-120': '/posts/psalm-120-in-the-tents-of-kedar-and-the-meccan-persecution',
  '/posts/psalm-144-is-missing-6-paragraphs-is-this-a-distortion-or-not': '/posts/psalm-144-in-codex-sinaiticus-missing-verses-or-psalm-numbering-confusion',
  '/posts/as-if-it-is-ascending-to-the-sky': '/posts/quran-6-125-refutes-the-doubt-does-ascending-into-the-sky-really-mean-rising-upward',
  '/posts/the-suspicion-of-bringing-the-plural-instead-of-the-dual': '/posts/quran-66-4-your-hearts-why-the-plural-replaces-the-dual',
  '/posts/did-the-quran-copy-from-the-apocryphal-gospels-a-complete-refutation-with-academic-sources': '/posts/quran-and-the-apocryphal-gospels-plagiarism-claim-refuted',
  '/posts/31-common-contradiction-in-quran-refuted': '/posts/quran-contradictions-debunked-days-of-creation-intercession-alcohol-and-more',
  '/posts/quranic-miracle-of-deep-sea-darkness-waves-above-waves-in-surah-an-nur-40': '/posts/qurans-layered-darkness-in-deep-seas-scientific-miracle',
  '/posts/what-is-the-legal-ruling-on-the-crime-of-rape': '/posts/rape-in-islamic-law-punishment-evidence-and-protection',
  '/posts/bukhari-4557': '/posts/refuting-the-chains-around-their-necks-misinterpretation-in-sahih-al-bukhari-4557',
  '/posts/on-the-authority-of-ibn-abbas-he-used-to-say-regarding-the-almightys-saying-and-your-lord-has-dec': '/posts/refuting-the-claim-that-and-your-lord-has-decreed-in-al-isra-17-23-is-a-scribal-error',
  '/posts/marriage-to-zainab-quick-version': '/posts/refuting-the-claim-that-the-prophet-صلى-الله-عليه-وسلم-desired-his-adopted-sons-wife-the-story-of-zainab-bint-jahsh',
  '/posts/nasai-3959': '/posts/refuting-the-claim-that-the-prophet-صلى-الله-عليه-وسلم-was-intimate-with-mariyah-in-hafsahs-house-on-her-day-the-correct-understanding-of-surah-at-tahrim',
  '/posts/update-2026-1468269937515823264': '/posts/refuting-the-dirham-anachronism-how-the-quran-accurately-describes-ancient-currency',
  '/posts/foreign-terms-in-the-holy-quran': '/posts/refuting-the-orientalist-claim-that-the-quran-contains-foreign-words-borrowed-from-syriac-hebrew-and-aramaic',
  '/posts/repeating-then-which-of-the-favors-of-your-lord-would-you-deny': '/posts/repetition-in-the-quran-a-literary-and-religious-virtue-not-a-defect-with-parallel-evidence-from-the-bible',
  '/posts/why-is-there-repetition-in-quran': '/posts/repetition-in-the-quran-weakness-or-eloquence-a-complete-refutation',
  '/posts/star-wars-and-teenage-mutant-ninja-turtles': '/posts/revelation-1213-a-critical-examination-of-the-dragon-the-beast-and-the-woman',
  '/posts/the-response-to-the-doubt-about-the-rooster-that-ate-the-quran': '/posts/rooster-ate-quran-verses-preservation-and-hadith-weakness',
  '/posts/prophets-marriage-to-safiyya-quick-version': '/posts/safiyya-bint-huyayy-the-distorted-word-the-biblical-double-standard-and-her-own-testimony',
  '/posts/bukhari-4697': '/posts/sahih-al-bukhari-4697-explained-context-and-correct-understanding',
  '/posts/bukharis-manuscripts': '/posts/sahih-al-bukhari-transmission-chains-manuscript-history-authentication-methodology-and-the-narrators-who-were-criticized',
  '/posts/deception-no-25-you-will-follow-the-ways-of-those-before-you-inch-by-inch': '/posts/sahih-bukhari-3197-following-previous-nations-explained',
  '/posts/deception-no-29-he-rudely-replies-to-muhammad-that-he-is-not-crazy': '/posts/sahih-bukhari-6115-anger-and-seeking-refuge-from-satan',
  '/posts/finally-saint-cyril-the-great-solved-the-problem-of-the-christians-orders-to-slaughter-infants-and': '/posts/saint-cyril-on-killing-children-the-biblical-problem-christians-cannot-escape',
  '/posts/satan-plays-with-the-private-parts-of-the-children-of-adam': '/posts/satan-plays-with-the-private-parts-hadith-grading-and-refutation',
  '/posts/sahih-bhukari-146': '/posts/sawdah-and-the-veil-omars-jealousy-not-harassment',
  '/posts/scientific-errors': '/posts/scientific-errors-in-the-bible-a-comprehensive-examination',
  '/posts/inquiry-about-selling-the-mother-of-a-child-and-marrying-a-chaste-right-hand-slave-hadiths': '/posts/selling-umm-al-walad-sex-with-captives-and-khalid-ibn-al-walid-answering-three-major-misconceptions-about-islam',
  '/posts/common-15-claims': '/posts/sixteen-christian-arguments-for-the-divinity-of-christ-a-complete-refutation-from-the-bible-itself',
  '/posts/slavery-and-concubinage-endorsed-by-the-bible-1354004700260733043': '/posts/slavery-concubines-and-war-captives-in-the-bible-the-christian-double-standard',
  '/posts/slavery-quick-version': '/posts/slavery-in-islam-islamic-law-vs-western-systems-explained',
  '/posts/pagan-origins-of-christianity-the-sun-symbol': '/posts/sol-invictus-to-jesus-how-constantine-replaced-the-pagan-sun-god-with-christ',
  '/posts/what-is-the-punishment-for-a-married-adulterer': '/posts/stoning-in-islam-evidence-from-quran-sunnah-and-bible',
  '/posts/criminal-punishments-in-the-bible': '/posts/strange-rulings-in-the-torah-a-critical-examination-of-biblical-civil-criminal-and-ritual-law',
  '/posts/sunset-in-ain-hamia': '/posts/sun-setting-in-a-spring-hadith-weakness-and-meaning',
  '/posts/more-questions-asked-about-it-summary-of-debate': '/posts/surah-al-rum-prophecy-refuted-answering-the-badr-hadith-and-ghalabat-reading-doubt',
  '/posts/lowest-point-of-earth': '/posts/surah-ar-rum-predicted-the-lowest-point-on-earth-1400-years-before-satellite-surveys',
  '/posts/figt-those-wo': '/posts/surah-at-tawbah-29-explained-jizya-fighting-and-subjugation',
  '/posts/so-today-we-will-save-you-with-your-body-that-you-may-be-a-sign-to-those-who-come-after-you': '/posts/surah-yunus-92-and-the-mummy-of-ramses-ii-marine-sand-broken-bones-and-the-sign-that-endures',
  '/posts/a-woman-comes-in-the-form-of-a-devil': '/posts/tabarruj-in-islam-what-the-quran-hadith-and-classical-scholars-say-about-womens-modesty',
  '/posts/does-tacitus-testimony-prove-the-crucifixion-of-christ-historically-a-response-to-the-delulu': '/posts/tacitus-on-the-crucifixion-of-christ-why-the-annals-15-44-is-not-historical-evidence',
  '/posts/the-problem-of-the-letter-alif-in-some-verses-of-the-quran': '/posts/the-alif-of-pause-in-quranic-recitation-linguistic-evidence-and-reader-positions',
  '/posts/pagan-origins-of-christianity-the-shape-of-the-ark-of-the-covenant-ark-of-the-lord': '/posts/the-ark-of-the-covenant-was-copied-from-egyptian-pharaonic-coffins',
  '/posts/18-the-holy-bible-teaches-the-christian-how-to-r-pe-his-sister-and-also-the-trap-that-he-sets-fo': '/posts/the-bible-contains-explicit-sexual-narratives-and-morally-problematic-stories',
  '/posts/responding-to-the-allegation-of-similarity-between-the-birth-of-mithras-and-the-prophet-isa-peace': '/posts/the-birth-of-mithras-vs-the-birth-of-jesus-in-the-quran-a-refutation-of-the-similarity-claim',
  '/posts/the-dung-of-camel-smells-like-musk': '/posts/the-camel-dung-narration-a-hadith-criticism-response',
  '/posts/age-argument-omar': '/posts/the-covenant-of-umar-explained-refuting-christian-polemics-against-islam',
  '/posts/the-miracle-in-the-almightys-saying-he-said-your-appointment-is-the-day-of-adornment': '/posts/the-day-of-adornment-in-the-quran-the-pharaonic-festival-that-confirms-divine-revelation',
  '/posts/the-devil-urinates': '/posts/the-devil-urinates-in-the-ear-understanding-the-hadith-mocked-by-critics',
  '/posts/as-an-example-who-wrote-it-in-response-to-the-theological-defense-team': '/posts/the-epistle-to-the-hebrews-who-wrote-it',
  '/posts/talking-donkey': '/posts/the-fabricated-talking-donkey-hadith-and-the-bibles-speaking-animals',
  '/posts/20-evidences-that-lie-the-story': '/posts/the-false-attribution-of-the-story-of-david-and-uriahs-wife-to-the-quran',
  '/posts/then-bite-him-with-them-his-father-and-do-not-use-euphemisms-and-did-the-prophet-command-that-some': '/posts/the-fathers-penis-hadith-why-its-weak-misread-mistranslated-a-complete-response',
  '/posts/the-effect-of-the-last-presentation-on-the-collection-of-the-quran': '/posts/the-final-presentation-to-gabriel-basis-for-the-uthmanic-collection',
  '/posts/genealogy-of-muhammad': '/posts/the-genealogy-of-prophet-muhammad-صلى-الله-عليه-وسلم-from-ishmael-to-the-final-prophet',
  '/posts/the-writer-of-the-gospel-of-luke-the-unknown-person-condition-time-and-place-wrote-his-gospe': '/posts/the-gospel-of-luke-unknown-author-human-sources-and-late-dating-problems',
  '/posts/fatima-and-muhammads-wives-are-working-as-parties-and-accuse-him-of-injustice': '/posts/the-hadith-of-aisha-and-the-gifts-the-prophets-special-love-for-aisha-and-what-it-teaches-about-justice-among-wives',
  '/posts/the-response-to-the-allegation-that-god-sits-on-a-throne-and-creaks-like-a-saddle': '/posts/the-hadith-of-the-creaking-throne-a-complete-chain-by-chain-refutation',
  '/posts/the-weak-one-who-has-no-support': '/posts/the-hadith-of-the-people-of-paradise-and-hell-meaning-of-zabr',
  '/posts/deception-no-15-men-who-extinguish-the-sunnah-and-create-innovation': '/posts/the-hadith-of-unjust-rulers-delaying-prayer-explained',
  '/posts/update-1340752533714501730': '/posts/the-hadith-on-gender-determination-a-scientific-analysis',
  '/posts/i-drank-from-his-ablution-water': '/posts/the-healing-miracles-of-prophet-muhammad-evidence-of-prophethood-and-comparison-with-gospel-accounts',
  '/posts/sahih-muslim-2898a': '/posts/the-hour-will-be-established-while-the-romans-are-the-majority-al-nawawi-al-qurtubi-explain',
  '/posts/deception-no-10-the-companions-who-tried-to-kill-him-pbuh': '/posts/the-hypocrites-who-plotted-against-prophet-muhammad-after-tabuk',
  '/posts/scholars-n-jihad-response': '/posts/the-islamic-rules-of-warfare-protecting-the-people-of-the-covenant-women-and-children',
  '/posts/genealogy-of-prophet-related-doubts-quick-version': '/posts/the-lineage-of-the-prophet-muhammad-صلى-الله-عليه-وسلم-established-from-heritage-books-and-refuting-the-4-year-pregnancy',
  '/posts/secret-of-the-disconnected-letters': '/posts/the-miraculous-nature-of-the-quran-the-disconnected-letters-and-the-inimitability-of-the-divine-word',
  '/posts/the-miracle-of-the-shadow-in-the-quran-documented-by-national-geographic': '/posts/the-moving-shadow-in-the-quran-al-furqan-45-and-the-science-of-light',
  '/posts/sham-el-nessim-is-a-pagan-holiday': '/posts/the-pagan-roots-of-sham-el-nessim-an-islamic-warning-against-imitation',
  '/posts/the-people-of-the-elephant': '/posts/the-people-of-the-elephant-non-muslim-historical-sources-confirm-surah-al-fil',
  '/posts/reply-to-naked-dragging-his-garment': '/posts/the-prophet-and-zaid-ibn-haritha-the-nakedness-hadith-examined',
  '/posts/aisha-broke-plates': '/posts/the-prophet-صلى-الله-عليه-وسلم-aishas-jealousy-and-the-bowl-incident-refuting-claims-of-lust-and-misconduct',
  '/posts/messenger-applied-light-and-turned-his-pubic-hair-with-his-hand': '/posts/the-prophet-صلى-الله-عليه-وسلم-and-depilatory-cream-hadith-analysis-refutation',
  '/posts/muhammad-peace-be-upon-him-wanted-to-tie-the-devils-demons-and-jinn-to-the-pillars-of-the-mosque': '/posts/the-prophet-صلى-الله-عليه-وسلم-and-the-jinn-at-the-mosque-the-hadith-of-tying-the-devil-explained',
  '/posts/the-miracle-of-the-unseen-in-fat-will-appear-in-them': '/posts/the-prophet-صلى-الله-عليه-وسلم-predicted-the-obesity-epidemic-1400-years-ago',
  '/posts/the-noble-messenger-used-to-urinate-while-sitting-is-there-anyone-who-objects': '/posts/the-prophet-صلى-الله-عليه-وسلم-urinating-while-sitting-the-wisdom-the-evidence-and-the-modern-scientific-confirmation',
  '/posts/untitled-1319706865596371084': '/posts/the-prophets-mercy-how-islam-treats-people-of-other-faiths',
  '/posts/lslam-attitude-towards-non-muslim': '/posts/the-prophets-mercy-how-islam-treats-people-of-other-faiths',
  '/posts/the-suspicion-of-the-camels-mention-in-the-time-of-joseph-peace-be-upon-him-and-the-miracle': '/posts/the-quran-and-camels-in-josephs-time-a-historical-miracle-not-an-error',
  '/posts/the-quran-is-one-thousand-and-twenty-seven-thousand-letters': '/posts/the-quran-has-1027000-letters-is-this-hadith-authentic',
  '/posts/the-danger-of-usury-testimonials-from-non-muslims': '/posts/the-quran-was-right-non-muslim-scholars-economists-us-senate-reports-on-the-harm-of-usury',
  '/posts/quran-n-hail': '/posts/the-qurans-mention-of-hail-and-snow',
  '/posts/the-holy-quran-is-transmitted-to-us-by-hearing-and-receiving-from-one-heart-to-another': '/posts/the-qurans-oral-transmission-why-memorization-outranks-the-written-text',
  '/posts/response-to-the-evidence-on-the-recurrent-laryngeal-nerve': '/posts/the-recurrent-laryngeal-nerve-is-it-evidence-of-poor-design-a-scientific-rebuttal',
  '/posts/samaritan-error-archeological-error': '/posts/the-samaritan-anachronism-debunked-al-samiri-in-the-quran-and-the-true-origins-of-the-samaritans',
  '/posts/lie-of-satanic-verses': '/posts/the-satanic-verses-story-a-fabrication-full-scholarly-refutation',
  '/posts/the-satanic-verses-incident-refuted-weak-chains-fabricated-reports-quranic-preservation': '/posts/the-satanic-verses-story-a-fabrication-full-scholarly-refutation',
  '/posts/the-satanic-verses-incident-refuted-weak-chains-fabricated-reports': '/posts/the-satanic-verses-story-a-fabrication-full-scholarly-refutation',
  '/posts/ajwa-dates': '/posts/the-seven-ajwa-dates-does-the-prophet-being-bewitched-disprove-the-hadith',
  '/posts/majah-1944-sheep-eating': '/posts/the-sheep-ate-the-quran-claim-refuted-why-sunan-ibn-majah-1944-is-rejected-in-hadith-sciences',
  '/posts/who-is-speaking-in-surat-al-fatihah': '/posts/the-shift-from-third-person-to-second-person-in-surah-al-fatihah-linguistic-error-or-rhetorical-mastery',
  '/posts/bond-women-awrah': '/posts/the-slave-girls-awrah-in-islamic-jurisprudence-a-complete-analysis',
  '/posts/women-rights': '/posts/the-status-of-women-among-islamic-jurists',
  '/posts/the-stoning-verse-is-not-found-in-the-quran': '/posts/the-stoning-verse-why-it-was-abrogated-from-recitation',
  '/posts/sexual-words-hadiths': '/posts/the-story-of-maiz-ibn-malik-the-prophets-mercy-and-the-strict-conditions-for-proving-adultery',
  '/posts/marriage-to-safiyya': '/posts/the-story-of-safiyya-bint-huyayy-mother-of-the-believers-not-a-captive-taken-by-force',
  '/posts/beginners-guide-to-hadeeth-sunnah': '/posts/the-sunnah-and-hadith-meaning-importance-and-preservation',
  '/posts/the-sun-prostrates-under-the-throne': '/posts/the-suns-prostration-quranic-cosmology-and-modern-astronomy',
  '/posts/and-we-decreed-to-the-children-of-israel-in-the-scripture-you-will-surely-cause-corruption-on-the': '/posts/the-testament-of-moses-prophecy-did-it-predict-prophet-muhammad-صلى-الله-عليه-وسلمs-birth',
  '/posts/mutah-pleasure-marriage': '/posts/the-truth-about-mutah-temporary-marriage-permanently-forbidden-in-quran-sunnah-full-evidence',
  '/posts/he-fabricated-a-lie-against-ibn-abbas-may': '/posts/the-weak-chain-behind-the-claim-that-ikrimah-lied-against-ibn-abbas',
  '/posts/well-of-buda-dawood-67': '/posts/the-well-of-budhaah-hadith-does-islam-permit-ablution-with-filthy-water',
  '/posts/deception-no-11-there-are-12-hypocrites-among-my-companions': '/posts/twelve-hypocrites-vs-the-sahabah-a-refutation',
  '/posts/kufrcleaner-article': '/posts/two-unanswered-challenges-abu-lahab-and-the-splitting-of-the-moon',
  '/posts/attributes-of-god-in-the-old-testament': '/posts/unworthy-attributes-of-god-in-the-old-testament-fatigue-weakness-ignorance-regret-and-forgetfulness',
  '/posts/sword-n-violent-verses-in-bible': '/posts/violence-and-killing-in-the-bible-a-complete-verse-by-verse-record',
  '/posts/story-of-dhul-qarnayn-was-borrowed-from-syriac-sources': '/posts/was-dhul-qarnayn-borrowed-from-the-alexander-legend-a-refutation-of-the-syriac-source-theory',
  '/posts/is-hajj-a-pagan-ritual-taken-from-hindus': '/posts/was-islamic-hajj-borrowed-from-hinduism-full-refutation-of-the-hindu-ritual-claim',
  '/posts/juspius-flavius-and-the-13-jesus': '/posts/was-jesus-a-unique-name-the-13-men-named-jesus-in-josephus-flavius',
  '/posts/is-pharaohs-divinity-in-the-quran-taken-from-the-madras': '/posts/was-pharaohs-divinity-in-the-quran-copied-from-the-midrash-a-chronological-refutation',
  '/posts/non-islamic-sources-regarding-the-prophet-muhammads-saw-being-unlettered': '/posts/was-prophet-muhammad-illiterate-non-islamic-sources-on-the-unlettered-prophet',
  '/posts/cave-story-borrowed': '/posts/was-the-cave-of-thawr-story-borrowed-from-saint-felix',
  '/posts/6-days-of-creation': '/posts/was-the-creation-six-days-or-eight',
  '/posts/you-follow-none-but-a-man-bewitched-al-isra-47-negate-or-confirm-the-prophets-bewitchment': '/posts/was-the-prophet-صلى-الله-عليه-وسلم-really-bewitched-refuting-the-quran-hadith-contradiction-claim',
  '/posts/refuting-claims-that-the-quran-was-copied-from-zoroastrian-and-jewish-sources': '/posts/was-the-quran-copied-from-jewish-and-zoroastrian-sources-7-claims-refuted-with-historical-evidence',
  '/posts/may-god-bless': '/posts/was-the-revelation-in-the-cave-of-hira-a-dream-a-complete-refutation',
  '/posts/either-believe-in-the-trinity-or-be-burned-this-is-how-the-church-spread-the-doctrine-of-the-trinit': '/posts/was-the-trinity-spread-by-proof-or-by-fire-the-story-of-michael-servetus',
  '/posts/update-1342464262139809902': '/posts/were-the-bones-created-first-or-the-flesh',
  '/posts/condition-of-peoples-and-countries-under-roman-and-persian-rule-before-the-islamic-conquest': '/posts/were-the-islamic-conquests-oppressive-how-rome-and-persia-actually-treated-egypt-syria-and-the-levant',
  '/posts/the-lie-that-the-prophet-ordered-the-sucking-of-genitals': '/posts/what-is-the-meaning-of-until-he-tastes-her-honey-in-the-halala-hadith-refuting-the-oral-sex-allegation-against-the-prophets-hadith',
  '/posts/testimonies-of-non-muslims': '/posts/what-non-muslims-said-about-prophet-muhammad-testimonies-from-historians-scholars',
  '/posts/allah-almighty-gave-good-tidings-to-abraham-peace-be-upon-him-of-a-forbearing-boy-and-in-anothe': '/posts/which-of-abrahams-two-sons-was-the-forbearing-boy-and-which-was-the-knowledgeable-boy',
  '/posts/burning-of-the-library-of-alexandria': '/posts/who-really-destroyed-the-library-of-alexandria-the-myth-against-muslims-exposed',
  '/posts/who-was-the-first-muslim-abraham-moses-or-the-magicians-quranic-contradiction-refuted': '/posts/who-was-the-first-muslim-refuting-the-quranic-contradiction-claim',
  '/posts/revelation-of-john-who-wrote-it-and-when-did-it-become-canonical-and-part-of-the-new-testament': '/posts/who-wrote-the-book-of-revelation-the-unknown-author-the-church-has-debated-for-centuries',
  '/posts/gospel-of-matthew-who-wrote-it': '/posts/who-wrote-the-gospel-of-matthew-scholars-confirm-the-author-is-unknown-and-was-not-the-apostle-matthew',
  '/posts/if-you-capture-a-jewish-man-kill-him': '/posts/whoever-you-find-among-the-jewish-men-kill-him-complete-chain-of-transmission-analysis-proving-all-paths-are-weak',
  '/posts/why-did-god-create-pigs-and-then-forbid-them-the-importance-of-harmful-and-harmful-animals': '/posts/why-did-god-create-pigs-if-theyre-forbidden-the-hidden-purpose-of-harmful-animals-in-islam',
  '/posts/and-then-sends-a-prophet': '/posts/why-did-god-leave-people-for-600-years-before-sending-prophet-muhammad',
  '/posts/anektaha': '/posts/why-did-prophet-muhammad-صلى-الله-عليه-وسلم-say-أنكتها-anektha-in-sahih-bukhari-a-linguistic-and-legal-refutation',
  '/posts/we-have-killed-the-messiah-jesus-the-son-of-mary-the-messenger-of-god': '/posts/why-did-the-jews-call-jesus-messiah-if-they-didnt-believe-in-him-the-quranic-answer-explained',
  '/posts/why-did-the-quran-mention-the-masculine-word-obedient-when-referring-to-the-wives-of-the-prophet': '/posts/why-did-the-quran-use-masculine-yaqnut-for-the-prophets-wives-full-linguistic-answer',
  '/posts/uthman-ibn-affan-and-the-holy-quran-revisited': '/posts/why-did-uthman-burn-other-quran-copies-the-uthmanic-codex-and-preservation-of-the-quran',
  '/posts/did-god-fail-to-preserve-the-previous-books': '/posts/why-didnt-allah-preserve-the-bible-and-torah-quran-15-9-and-the-trust-given-to-ahl-al-kitab',
  '/posts/circumcision-a-medical-and-legislative-miracle-in-the-final-message': '/posts/why-islam-prescribed-circumcision-modern-medicine-confirms-the-sunnah',
  '/posts/why-was-the-quran-not-compiled-during-the-era-of-the-prophet': '/posts/why-was-the-quran-not-compiled-during-the-prophets-lifetime-the-doubt-answered',
  '/posts/untitled-1319668747341926410': '/posts/women-rights-before-islam',
  '/posts/inheritance-is-half-that-of-the-males': '/posts/womens-inheritance-in-islam-the-half-share-rule-is-not-universal-and-islam-gave-women-more-than-any-prior-system',
  '/posts/a-womans-testimony-alone': '/posts/womens-testimony-in-islam-why-two-women-half-a-mind-the-complete-scholarly-analysis-from-ibn-taymiyyah-to-mahmoud-shaltut',
  '/posts/watering-egypt-with-rain': '/posts/yaghāth-and-yaṣirūn-rain-and-pressing-in-pharaohs-dream'
} : {},
image: {
    service: {
      entrypoint: 'astro/assets/services/sharp',
      config: {
        limitInputPixels: false,
      }
    },
    remotePatterns: []
  },
  integrations: [
    pagefind(),
    refreshContentOnChange(),
    tailwind(),
    sitemap(),
    swup({
      theme: false,
      animationClass: 'transition-swup-',
      containers: ['#swup-container'],
      smoothScrolling: false,
      cache: process.env.NODE_ENV === 'production', // off in dev so post edits show immediately
      preload: true,
      accessibility: false,
      updateHead: true,
      updateBodyClass: false,
      globalInstance: true,
      reloadScripts: false, // SwupScriptsPlugin breaks ES module scripts (import X as Y syntax error)
      plugins: [] // Disable all plugins including scroll
      // NOTE: swup-core options like skipPopStateHandling/linkSelector are NOT
      // forwarded by @swup/astro (see its Options interface) — Swup handles
      // browser back/forward itself (default popstate handling, no animation)
      // and fires page:view → astro:page-load on every history navigation.
    })
  ],
  markdown: {
      // Clean #fn-1 / #fnref-1 footnote anchors. The default 'user-content-'
      // prefix is GitHub's DOM-clobbering guard for untrusted comment HTML —
      // pointless for our own content. (Marginalia ids are mn-* to stay clear.)
      remarkRehype: { clobberPrefix: '' },
      remarkPlugins: [
      remarkCitations,          // Process [@citation-key] inline citations
      remarkObsidianImageSize, // Parse Obsidian image size syntax first
      [remarkInternalLinks, { base: '/' }],
      remarkInlineTags,
      remarkObsidianComments, // Remove Obsidian comments (%%...%%) early in processing
      remarkMarginalia,       // Parse {{marginalia}} side notes (⟪...⟫ in .mdx normalized internally)
      remarkAnnotations,      // Parse ::text{type}:: rough-notation annotations
      remarkFolderImages,
      remarkObsidianEmbeds,
      // Bases directive (table-only v1)
      remarkBases,
      remarkImageCaptions,
      remarkMath,
      remarkRescueCurrency,
      remarkCallouts,
      remarkBreaks,
      remarkImageGrids,
      remarkMermaid,
      [remarkReadingTime, {}],
      [remarkToc, {
        tight: true,
        ordered: false,
        maxDepth: 3,
        heading: 'contents|table[ -]of[ -]contents?|toc'
      }],
    ],
    rehypePlugins: [
      rehypeKatex,
      rehypeMark,
      rehypeImageAttributes,
      rehypeFigureCaptions,
      [rehypeSlug, {
        test: (node) => node.tagName !== 'h1'
      }],
      rehypeHeadingHighlight,
      [rehypeAutolinkHeadings, {
        behavior: 'append',
        test: (node) => node.tagName !== 'h1',
        properties: {
          'data-role': 'anchor',
          'data-no-swup': '',
          ariaLabel: 'Link to this section',
        },
        content: {
          type: 'element',
          tagName: 'svg',
          properties: {
            xmlns: 'http://www.w3.org/2000/svg',
            width: 16,
            height: 16,
            viewBox: '0 0 24 24',
            fill: 'none',
            stroke: 'currentColor',
            strokeWidth: '2',
            strokeLinecap: 'round',
            strokeLinejoin: 'round',
            ariaHidden: 'true',
          },
          children: [
            {
              type: 'element',
              tagName: 'path',
              properties: { d: 'M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71' },
              children: [],
            },
            {
              type: 'element',
              tagName: 'path',
              properties: { d: 'M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71' },
              children: [],
            },
          ],
        },
      }],
      rehypeNormalizeAnchors, // Run LAST to ensure className and href fixes aren't overridden
    ],
    shikiConfig: {
      theme: 'github-dark',
      wrap: true
    }
  },
  vite: {
    assetsInclude: ['**/*.base', '**/*.home', '**/*.base'],
    build: {
      rollupOptions: {
        external: ['/pagefind/pagefind.js'],
      },
    },
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
        '@/components': fileURLToPath(new URL('./src/components', import.meta.url)),
        '@/layouts': fileURLToPath(new URL('./src/layouts', import.meta.url)),
        '@/utils': fileURLToPath(new URL('./src/utils', import.meta.url)),
        '@/types': fileURLToPath(new URL('./src/types.ts', import.meta.url)),
        '@/config': fileURLToPath(new URL('./src/config.ts', import.meta.url)),
        '@/graph':  fileURLToPath(new URL('./src/graph', import.meta.url))
      }
    },
    server: {
      host: 'localhost',
      port: 5000,
      strictPort: false, // Allow fallback to 5001 if 5000 is occupied (e.g., AirPlay on macOS)
      allowedHosts: [],
      middlewareMode: false,
      hmr: true,
      watch: {
        ignored: ['**/.obsidian/**', '**/_bases/**', '**/bases/**'],
        usePolling: process.platform === 'win32',
        interval: 1000
      },
      headers: {
        'Cache-Control': 'no-store, no-cache, must-revalidate, max-age=0'
        // CSP headers are handled by src/middleware.ts for all routes
      }
    },
    define: {
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
    },
    optimizeDeps: {
      exclude: ['astro:content'],
      include: ['d3-force', 'rough-notation']
    },
    exclude: ['**/_redirects']
  },
  build: {
    assets: '_assets'
  }
});




