import { visit, SKIP } from 'unist-util-visit';
import type { Plugin } from 'unified';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

// mdast types are available at runtime via remark — inline the minimal types needed
type Root = import('unist').Parent & { type: 'root' };
type Text = { type: 'text'; value: string; [key: string]: unknown };

// Matches [@citation-key] syntax in body text
const CITATION_REGEX = /\[@([a-zA-Z0-9_:.-]+)\]/g;

// Load global-refs.json once at module init (generated by scripts/parse-bib.mjs)
let _globalRefMap: Map<string, Record<string, unknown>> | null = null;
function getGlobalRefMap(): Map<string, Record<string, unknown>> {
  if (_globalRefMap !== null) return _globalRefMap;
  _globalRefMap = new Map();
  try {
    const refPath = join(process.cwd(), 'src/data/global-refs.json');
    if (existsSync(refPath)) {
      const entries: Array<{ id: string } & Record<string, unknown>> = JSON.parse(readFileSync(refPath, 'utf-8'));
      entries.forEach(e => { if (e?.id) _globalRefMap!.set(e.id, e); });
    }
  } catch {
    // global-refs.json not yet generated — citations fall back to '?'
  }
  return _globalRefMap;
}

const remarkCitations: Plugin<[], Root> = function () {
  return function (tree, vfile) {
    const frontmatter = (vfile.data as any)?.astro?.frontmatter;
    const fmRefs: Array<{ id: string }> = frontmatter?.references ?? [];

    // Build refMap from frontmatter refs (numbered by frontmatter order)
    const refMap = new Map<string, number>();
    fmRefs.forEach((ref, i) => {
      if (ref?.id) refMap.set(ref.id, i + 1);
    });

    // Pass 1 (read-only): collect all [@key] occurrences from text nodes
    // so global refs can fill in keys not present in frontmatter
    const globalMap = getGlobalRefMap();
    const seenKeys: string[] = [];
    visit(tree, 'text', (node: Text) => {
      const value = node.value;
      if (!value.includes('[@')) return;
      CITATION_REGEX.lastIndex = 0;
      let m: RegExpExecArray | null;
      while ((m = CITATION_REGEX.exec(value)) !== null) {
        const id = m[1];
        if (!refMap.has(id) && globalMap.has(id) && !seenKeys.includes(id)) {
          seenKeys.push(id);
        }
      }
    });

    // Append global refs in first-occurrence order
    let nextNum = refMap.size + 1;
    for (const id of seenKeys) {
      refMap.set(id, nextNum++);
    }

    if (!refMap.size) return;

    // Pass 2 (mutating): replace [@key] text nodes with HTML superscript links
    visit(tree, 'text', (node: Text, index, parent) => {
      if (!parent || index == null) return;
      const value = node.value;
      if (!value.includes('[@')) return;

      CITATION_REGEX.lastIndex = 0;
      if (!CITATION_REGEX.test(value)) return;
      CITATION_REGEX.lastIndex = 0;

      const parts: any[] = [];
      let last = 0;
      let m: RegExpExecArray | null;

      while ((m = CITATION_REGEX.exec(value)) !== null) {
        if (m.index > last) {
          parts.push({ type: 'text', value: value.slice(last, m.index) });
        }
        const id = m[1];
        const num = refMap.has(id) ? refMap.get(id) : '?';
        parts.push({
          type: 'html',
          value: `<sup><a href="#ref-${id}" id="cite-${id}" class="cite-ref">[${num}]</a></sup>`,
        });
        last = m.index + m[0].length;
      }

      if (last < value.length) {
        parts.push({ type: 'text', value: value.slice(last) });
      }

      if (parts.length === 0) return;
      (parent.children as any[]).splice(index as number, 1, ...parts);
      return [SKIP, (index as number) + parts.length];
    });
  };
};

export default remarkCitations;
